{{- if .Values.rewardsService.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.rewardsService.name }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "mnbara.serviceLabels" (list . .Values.rewardsService.name) | nindent 4 }}
spec:
  type: {{ .Values.rewardsService.service.type }}
  ports:
    - port: {{ .Values.rewardsService.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "mnbara.serviceSelectorLabels" (list . .Values.rewardsService.name) | nindent 4 }}
{{- end }}
