{{- if .Values.notificationService.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.notificationService.name }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "mnbara.serviceLabels" (list . .Values.notificationService.name) | nindent 4 }}
spec:
  {{- if not .Values.notificationService.autoscaling.enabled }}
  replicas: {{ .Values.notificationService.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "mnbara.serviceSelectorLabels" (list . .Values.notificationService.name) | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "mnbara.serviceSelectorLabels" (list . .Values.notificationService.name) | nindent 8 }}
    spec:
      serviceAccountName: {{ include "mnbara.serviceAccountName" . }}
      containers:
        - name: {{ .Values.notificationService.name }}
          image: {{ include "mnbara.image" (dict "root" . "service" .Values.notificationService) }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.notificationService.service.port }}
              protocol: TCP
          env:
            - name: PORT
              value: {{ .Values.notificationService.env.PORT | quote }}
            - name: NODE_ENV
              value: {{ .Values.notificationService.env.NODE_ENV | quote }}
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ default (printf "%s-redis" (include "mnbara.fullname" .)) .Values.secrets.redis.existingSecret }}
                  key: redis-password
            - name: REDIS_URL
              value: {{ include "mnbara.redisUrl" . | quote }}
            - name: RABBITMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ default (printf "%s-rabbitmq" (include "mnbara.fullname" .)) .Values.secrets.rabbitmq.existingSecret }}
                  key: rabbitmq-password
            - name: RABBITMQ_URL
              value: {{ include "mnbara.rabbitmqUrl" . | quote }}
          envFrom:
            - configMapRef:
                name: {{ include "mnbara.fullname" . }}-common
          resources:
            {{- toYaml .Values.notificationService.resources | nindent 12 }}
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 5
            periodSeconds: 5
{{- end }}
